# Generated by Django 6.0.4 on 2026-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_location_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='base_price',
            field=models.FloatField(),
        ),
    ]
