# Generated by Django 6.0.4 on 2026-04-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gymclass_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedEquipments',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.equipment',),
        ),
    ]
