# Generated by Django 6.0.4 on 2026-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_damagedequipments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagedequipments',
            options={'verbose_name': 'Damaged Equipment', 'verbose_name_plural': 'Damaged Equipment'},
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
